<?php 
/**
 * ZF2 Buch Kapitel 4
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 4.17 view script
 * 
 * @package    Application
 */

?>
<div class="row">
<div class="span9">
<h1>Listing 4.17</h1>
<h3>Daten mit <code>Zend\Filter\StaticFilter</code> filtern</h3>
<pre>
&lt;?php
use Zend\Debug\Debug;
use Zend\Filter\StaticFilter;

$value = 'Heute bekam Luigi die 4. Bestellung: 2x Pizza Salami';

Debug::dump(StaticFilter::execute($value, 'Digits'));

Debug::dump(StaticFilter::execute(
    $value, 'Alnum', array('AllowWhiteSpace' => true)
));

Debug::dump(StaticFilter::execute(
    $value, 
    'Callback', 
    array(
        'Callback' => 'wordwrap',
        'CallbackParams' => '30',
    )
));
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Debug\Debug;
use Zend\Filter\StaticFilter;

$value = 'Heute bekam Luigi die 4. Bestellung: 2x Pizza Salami';

Debug::dump(StaticFilter::execute($value, 'Digits'));

Debug::dump(StaticFilter::execute(
    $value, 'Alnum', array('AllowWhiteSpace' => true)
));

Debug::dump(StaticFilter::execute(
    $value, 
    'Callback', 
    array(
        'Callback' => 'wordwrap',
        'CallbackParams' => '30',
    )
));
?>
</div>
</div>
