<?php 
/**
 * ZF2 Buch Kapitel 4
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 4.6 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 4.6</h1>
<h3>Schreiben einer Konfigurationsdatei im YAML-Format</h3>
<pre>
&lt;?php 
// setup autoloading
require_once LUIGI_ROOT . '/vendor/autoload.php';

// set input file
$input  = LUIGI_ROOT . '/module/Pizza/config/module.config.ini';
$output = LUIGI_ROOT . '/data/config/module.config.yaml';

// read config file
$reader = new Zend\Config\Reader\Ini();
$config = $reader->fromFile($input);

// write config file
$writer = new Zend\Config\Writer\Yaml();
$writer->toFile($output, $config);

// output config data
Zend\Debug\Debug::dump($config);
</pre>
<h3>Ausgabe</h3>
<?php 
// set input file
$input  = LUIGI_ROOT . '/module/Pizza/config/module.config.ini';
$output = LUIGI_ROOT . '/data/config/module.config.yaml';

// read config file
$reader = new Zend\Config\Reader\Ini();
$config = $reader->fromFile($input);

// write config file
$writer = new Zend\Config\Writer\Yaml();
$writer->toFile($output, $config);

// output config data
Zend\Debug\Debug::dump($config);
?>
</div>
</div>
