<?php 
/**
 * ZF2 Buch Kapitel 4
 * 
 * Das Buch "Zend Framework 2 - Von den Grundlagen bis zur fertigen Anwendung"
 * von Ralf Eggert ist im Addison-Wesley Verlag erschienen. 
 * ISBN 978-3-8273-2994-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.awl.de/2994
 */

/**
 * Listing 4.22 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 4.22</h1>
<h3>Daten mit <code>Zend\Validator\StaticValidator</code> validieren</h3>
<pre>
&lt;?php
use Zend\Debug\Debug;
use Zend\Validator\StaticValidator;

$value1 = 'Hier dürfen nur Buchstaben stehen';
$value2 = 'Hier auch verdammt!';
Debug::dump(StaticValidator::execute(
    $value1, 'Alpha', array('AllowWhiteSpace' => true)
));
Debug::dump(StaticValidator::execute(
    $value2, 'Alpha', array('AllowWhiteSpace' => true)
));

$value1 = '978-3-8273-2994-3';
$value2 = '1-2345-6789-0';
Debug::dump(StaticValidator::execute(
    $value1, 'Isbn', array('separator' => '-')
));
Debug::dump(StaticValidator::execute(
    $value2, 'Isbn', array('separator' => '-')
));
</pre>
<h3>Ausgabe</h3>
<?php 
use Zend\Debug\Debug;
use Zend\Validator\StaticValidator;

$value1 = 'Hier dürfen nur Buchstaben stehen';
$value2 = 'Hier auch verdammt!';
Debug::dump(StaticValidator::execute(
    $value1, 'Alpha', array('AllowWhiteSpace' => true)
));
Debug::dump(StaticValidator::execute(
    $value2, 'Alpha', array('AllowWhiteSpace' => true)
));

$value1 = '978-3-8273-2994-3';
$value2 = '1-2345-6789-0';
Debug::dump(StaticValidator::execute(
    $value1, 'Isbn', array('separator' => '-')
));
Debug::dump(StaticValidator::execute(
    $value2, 'Isbn', array('separator' => '-')
));
?>
</div>
</div>
