<?php 
/**
 * ZF2 Buch Kapitel 4
 * 
 * Das Buch 'Zend Framework 2 - Das Praxisbuch'
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 4.19 view script
 * 
 * @package    Application
 */
?>
<div class='row'>
<div class='span9'>
<h1>Listing 4.19</h1>
<h3>Eigener <code>Revert</code> Filter</h3>
<pre>
&lt;?php
namespace Pizza\Filter;

use Zend\Filter\AbstractFilter;

class Revert extends AbstractFilter
{
    public function filter($value)
    {
        return strrev($value);
    }
}
</pre>
</div>
</div>
