<?php 
/**
 * ZF2 Buch Kapitel 4
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 4.2 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 4.2</h1>
<h3>Konfiguration <code>ClassMapAutoloader</code></h3>
<pre>
&lt;?php 
// setup autoloading
require_once LUIGI_ROOT . '/vendor/autoload.php';

// check if Pizza Salami can be loaded
Zend\Debug\Debug::dump(class_exists('Pizza\Model\PizzaSalami'));

// configure ClassMap Autoloader
$loader = new Zend\Loader\ClassMapAutoloader();
$loader->registerAutoloadMap(LUIGI_ROOT . '/module/Pizza/autoload_classmap.php');
$loader->register();

// check if Pizza Salami can be loaded
Zend\Debug\Debug::dump(class_exists('Pizza\Model\PizzaSalami'));
</pre>
<h3>Ausgabe</h3>
<?php echo $this->output; ?>
</div>
</div>
