<?php 
/**
 * ZF2 Buch Kapitel 4
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Listing 4.5 view script
 * 
 * @package    Application
 */
?>
<div class="row">
<div class="span9">
<h1>Listing 4.5</h1>
<h3>Lesen eines PHP-Arrays mit Hilfe von <code>Zend\Config\Config</code></h3>
<pre>
&lt;?php 
// setup autoloading
require_once LUIGI_ROOT . '/vendor/autoload.php';

// set input file
$input = LUIGI_ROOT . '/module/Pizza/config/module.config.php';

// read config file
$config = new Zend\Config\Config(include $input);

// output config data
Zend\Debug\Debug::dump($config->toArray());
</pre>
<h3>Ausgabe</h3>
<?php 
// set input file
$input = LUIGI_ROOT . '/module/Pizza/config/module.config.php';

// read config file
$config = new Zend\Config\Config(include $input);

// output config data
Zend\Debug\Debug::dump($config->toArray());
?>
</div>
</div>
