<?php 
/**
 * ZF2 Buch Kapitel 4
 * 
 * Das Buch "Zend Framework 2 - Das Praxisbuch"
 * von Ralf Eggert ist im Galileo-Computing Verlag erschienen. 
 * ISBN 978-3-8362-2610-3
 * 
 * @package    Application
 * @author     Ralf Eggert <r.eggert@travello.de>
 * @copyright  Alle Listings sind urheberrechtlich geschützt!
 * @link       http://www.zendframeworkbuch.de/ und http://www.galileocomputing.de/3460
 */

/**
 * Index view script
 * 
 * @package    Application
 */
?>
<h1>Listings - Kapitel 4</h1>
<table class="table table-bordered table-striped table-hover table-condensed">
<thead>
<tr>
<th>Listing</th>
<th>Beschreibung</th>
</tr>
</thead>
<tbody>
<tr>
<td><a href="/listing/listing0401">Listing 4.1</a></td>
<td>Konfiguration StandardAutoloader</td>
</tr>
<tr>
<td><a href="/listing/listing0402">Listing 4.2</a></td>
<td>Konfiguration ClassMapAutoloader</td>
</tr>
<tr>
<td><a href="/listing/listing0403">Listing 4.3</a></td>
<td>Konfiguration AutoloaderFactory</td>
</tr>
<tr>
<td><a href="/listing/listing0404">Listing 4.4</a></td>
<td>Lesen einer INI-Datei mit Hilfe von <code>Zend\Config\Reader</code></td>
</tr>
<tr>
<td><a href="/listing/listing0405">Listing 4.5</a></td>
<td>Lesen eines PHP-Arrays mit Hilfe von <code>Zend\Config\Config</code></td>
</tr>
<tr>
<td><a href="/listing/listing0406">Listing 4.6</a></td>
<td>Schreiben einer Konfigurationsdatei im YAML-Format</td>
</tr>
<tr>
<td><a href="/listing/listing0407">Listing 4.7</a></td>
<td>Cachen eines Objektes im Dateisystem mit <code>Zend\Cache</code></td>
</tr>
<tr>
<td><a href="/listing/listing0408">Listing 4.8</a></td>
<td>Ausgabe der unterstützten Datentypen</td>
</tr>
<tr>
<td><a href="/listing/listing0409">Listing 4.9</a></td>
<td>Einsatz des <code>ClassCache</code> Patterns</td>
</tr>
<tr>
<td><a href="/listing/listing0410">Listing 4.10</a></td>
<td>Logging von Pizzabelägen mit Logger, Writer und Formatter</td>
</tr>
<tr>
<td><a href="/listing/listing0411">Listing 4.11</a></td>
<td>Logging von Pizzabelägen mit Filtern</td>
</tr>
<tr>
<td><a href="/listing/listing0412">Listing 4.12</a></td>
<td>Erstellen einer E-Mail Nachricht mit <code>Zend\Mail</code></td>
</tr>
<tr>
<td><a href="/listing/listing0413">Listing 4.13</a></td>
<td>Versand einer E-Mail Nachricht über <code>Zend\Mail\Transport\File</code></td>
</tr>
<tr>
<td><a href="/listing/listing0414">Listing 4.14</a></td>
<td>Erstellen einer E-Mail Nachricht mit mehreren MIME-Parts</td>
</tr>
<tr>
<td><a href="/listing/listing0415">Listing 4.15</a></td>
<td>E-Mails von einem IMAP Server abrufen</td>
</tr>
<tr>
<td><a href="/listing/listing0416">Listing 4.16</a></td>
<td>Einsatz einiger Standardfilter aus <code>Zend\Filter</code></td>
</tr>
<tr>
<td><a href="/listing/listing0417">Listing 4.17</a></td>
<td>Daten mit <code>Zend\Filter\StaticFilter</code> filtern</td>
</tr>
<tr>
<td><a href="/listing/listing0418">Listing 4.18</a></td>
<td>Daten mit <code>Zend\Filter\FilterChain</code> filtern</td>
</tr>
<tr>
<td><a href="/listing/listing0419">Listing 4.19</a></td>
<td>Eigener <code>Revert</code> Filter</td>
</tr>
<tr>
<td><a href="/listing/listing0420">Listing 4.20</a></td>
<td>Eigenen <code>Revert</code> Filter einsetzen</td>
</tr>
<tr>
<td><a href="/listing/listing0421">Listing 4.21</a></td>
<td>Einsatz einiger Standardvalidatoren aus <code>Zend\Validator</code></td>
</tr>
<tr>
<td><a href="/listing/listing0422">Listing 4.22</a></td>
<td>Daten mit <code>Zend\Validator\StaticValidator</code> validieren</td>
</tr>
<tr>
<td><a href="/listing/listing0423">Listing 4.23</a></td>
<td>Daten mit <code>Zend\Validator\ValidatorChain</code> validieren</td>
</tr>
<tr>
<td><a href="/listing/listing0424">Listing 4.24</a></td>
<td>Eigener <code>PizzaName</code> Validator</td>
</tr>
<tr>
<td><a href="/listing/listing0425">Listing 4.25</a></td>
<td>Eigenen <code>PizzaName</code> Validator einsetzen</td>
</tr>
<tr>
<td><a href="/listing/listing0426">Listing 4.26</a></td>
<td>Fehlermeldungen für <code>PizzaName</code> Validator anpassen</td>
</tr>
</tbody>
</table>
